### ISSUE TITLE
valueAsDate = value as Date as needed, even when page refreshes

### ISSUE THREAD

**Issue by hchiam** [hchiam/form-utility-belt#77]
```txt
TypeError: Failed to set the 'valueAsDate' property on 'HTMLInputElement': The provided value is not a Date.
    at recursivelyTryCombos (content.js:493:46)
    at async recursivelyTryCombos (content.js:426:9)
```

**Comment by hchiam** [comment]
> ```
> TypeError: Failed to set the 'valueAsDate' property on 'HTMLInputElement': The provided value is not a Date.
>     at recursivelyTryCombos (content.js:493:46)
>     at async recursivelyTryCombos (content.js:426:9)
> ```

this only happens if the page refreshes partway through going through all combos
